name: Snake Contribution Graph

on:
  schedule:
    - cron: '0 * * * *' # Set the schedule as desired (every hour in this case)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Generate Snake Contribution Graph
        run: npx github-action-snake
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
